# Debug settings
debug: false

# HTTP endpoint URL for the AI
endpoint:
  answer-url: "http://localhost:8000/v2/answer"
  list-url: "http://localhost:8000/v2/list_documents"
  timeout: 30

# Knowledge filtering
source-filter:
  # Apply a filter to the knowledge source, for example a subfolder specific for this server on a network
  # NOTE: on google drive, the folder is the id of the folder, not the name (eg: 1v_DPY7mkRtx-_d7DH7EB86O9R2cKfWJc)
  folder: ""

# Tab settings
# NOTE: Requires Protocolib!!!
tab:
  enabled: true
  # Name of the helper displayed in the Tab
  name: "&bBattista AI Helper"

# Chat settings
chat:
  # AI helper responds when tagged in cha
  tagging:
    enabled: true
    # Tag for activation in chat (e.g., @Helper)
    tag: "@Helper"

  # Automatic question detection (looks for ? at the end of the message)
  auto_detect_questions:
    enabled: true
    min_length: 5
    max_length: 150

  # Prefix for AI responses
  response_prefix: "&7[&bAI Helper&7]&f "

messages:
  question_too_short: "&cYour question is too short! Please provide more details."
  question_too_long: "&cThe question is too long! Maximum 150 characters allowed."
  processing: "&eProcessing your question..."
  requesting_documents: "&eRequesting documents..."
  cant_process: "&cSorry, I cannot process your request at the moment. Please try again later."
  service_unavailable: "&cSorry, the AI service is currently unavailable, Error: "
  internal_error: "&cAn internal error occurred. Please contact an administrator."
  unknown_command: "&cUnknown subcommand. Use '/battista help' to see available commands."
  no_permission: "&cYou do not have permission to use this command!"
  empty_question: "&cYou do not have permission to use this command!"
  only_players: "&cOnly players can use this command!"
  realoaded: "&aBattista plugin configuration successfully reloaded!"
  not_realoaded: "&cAn error occurred while reloading the configuration!"
  help: |-
    &7Available commands:
    &b/battista reload &7- Reload the plugin configuration
    &b/battista documents &7- Lists documents that Battista uses as knowledge sources
    &b/battista help &7- Show this help message
    &b/ask &7- Ask a question to the AI Helper
  ask_usage: |-
    &cUsage: /ask <question>
    &bExample: /ask How do I craft a diamond sword?