# Debug settings
debug: false

# HTTP endpoint URL for the AI backend
# To archive optimal results, you should use Battista AI Backend, which MUST be installed separately from minecraft.
# It's a whole different application, more infos here: https://github.com/Manuel-Materazzo/battista-ai-backend
endpoint:
  answer-url: "http://localhost:8000/v2/answer"
  list-url: "http://localhost:8000/v2/list_documents"
  timeout: 30

# Knowledge filtering
source-filter:
  # Apply a filter to the knowledge source, for example a subfolder specific for this server on a network
  # NOTE: on google drive, the folder is the id of the folder, not the name (eg: 1v_DPY7mkRtx-_d7DH7EB86O9R2cKfWJc)
  folder: ""

# Tab settings
# NOTE: Requires Protocolib!!!
tab:
  # When enabled, shows Battista AI Helper as a player in the Tab
  enabled: true
  # Name of the helper displayed in the Tab
  name: "&bBattista AI Helper"

# Chat settings
chat:
  # AI helper responds when someone tags it in chat
  tagging:
    enabled: true
    # Tag for battista question detection in chat
    # An example of a message detected with the default tag would be: "@Helper what i have to do"
    tag: "@Helper"

  # Automatic question detection in chat (looks for ? at the end of the message)
  auto_detect_questions:
    enabled: true
    min_length: 5
    max_length: 150

  # Prefix for AI responses in chat
  response_prefix: "&7[&bAI Helper&7]&f "

# Limits to prevent abuse
limits:
  # Maximum time a player can idle in interactive mode (/ask wihout arguments) before the session is closed (in seconds)
  inteactive_timeout: 60

  # Global limits on AI helper use for all players combined
  ai_requests_global:
    requests_per_minute: 30
    requests_per_hour: 600
    requests_per_day: 1200

  # Limits on AI helper use for each player
  ai_requests_player:
    requests_per_minute: 3
    requests_per_hour: 60
    requests_per_day: 120

messages:
  question_too_short: "&cYour question is too short! Please provide more details."
  question_too_long: "&cThe question is too long! Maximum 150 characters allowed."
  processing: "&eProcessing your question..."
  requesting_documents: "&eRequesting documents..."
  cant_process: "&cSorry, I cannot process your request at the moment. Please try again later."
  service_unavailable: "&cSorry, the AI service is currently unavailable, Error: "
  internal_error: "&cAn internal error occurred. Please contact an administrator."
  unknown_command: "&cUnknown subcommand. Use '/battista help' to see available commands."
  no_permission: "&cYou do not have permission to use this command!"
  empty_question: "&cYou have to ask something!"
  only_players: "&cOnly players can use this command!"
  realoaded: "&aBattista plugin configuration successfully reloaded!"
  global_ratelimit_exceded: "&cSorry, the AI service is currently unavailable due to global rate limit exceeded."
  player_ratelimit_exceded: "&cSorry, you have exceeded the rate limit for AI requests. Please try again later."
  not_realoaded: "&cAn error occurred while reloading the configuration!"
  ask_interactive: "&7Hey, i'm Battista, the AI Helper! feel free to ask me anything! Just send a chat message and i'll respond to you!"
  ask_interactive_pending: "&7You already are on answer mode! just ask me anything without commands"
  ask_inteactive_timeout: "&7Ok, guess you don't want to ask anything. I'll be here if you need me! just use **/ask** again"
  help: |-
    &7Available commands:
    &b/battista reload &7- Reload the plugin configuration
    &b/battista documents &7- Lists documents that Battista uses as knowledge sources
    &b/battista help &7- Show this help message
    &b/ask &7- Ask a question to the AI Helper