# Debug settings
debug: false

# HTTP endpoint URL for the AI
endpoint:
  url: "http://localhost:8000/v2/answer"
  timeout: 30

# Chat settings
chat:
  # AI helper responds when tagged in cha
  tagging:
    enabled: true
    # Tag for activation in chat (e.g., @Helper)
    tag: "@Helper"

  # Automatic question detection (looks for ? at the end of the message)
  auto_detect_questions: true

  # Prefix for AI responses
  response_prefix: "&7[&bAI Helper&7]&f "

messages:
  question_too_short: "&cYour question is too short! Please provide more details."
  question_too_long: "&cThe question is too long! Maximum 150 characters allowed."
  processing: "&eProcessing your question..."
  cant_process: "&cSorry, I cannot process your request at the moment. Please try again later."
  service_unavailable: "&cSorry, the AI service is currently unavailable, Error: "
  internal_error: "&cAn internal error occurred. Please contact an administrator."
  unknown_command: "&cUnknown subcommand. Use '/battista help' to see available commands."
  no_permission: "&cYou do not have permission to use this command!"
  empty_question: "&cYou do not have permission to use this command!"
  only_players: "&cOnly players can use this command!"
  realoaded: "&aBattista plugin configuration successfully reloaded!"
  not_realoaded: "&cAn error occurred while reloading the configuration!"
  help: |-
    &7Available commands:
    &b/battista reload &7- Reload the plugin configuration
    &b/battista help &7- Show this help message
    &b/ask &7- Ask a question to the AI Helper
  ask_usage: |-
    &cUsage: /ask <question>
    &bExample: /ask How do I craft a diamond sword?
