name: Battista-Ai-Helper
version: 1.0.0
main: org.itsmanu.battistaAiSpigot.BattistaAiSpigot
api-version: 1.21
authors:
  - manuel-materazzo
description: A plugin AI helper that answers users' questions

commands:
  ask:
    description: Ask a question to the AI helper
    usage: /ask <question>
    permission: battista.use
  battista:
    description: Main command
    usage: /<command> [reload|help]
    permission: battista.use
permissions:
  battista.use:
    description: Basic permission to use the plugin
    default: true
  battista.reload:
    description: Plugin reload permission
    default: op
  battista.documents:
    description: Permission to list documents that Battista uses as knowledge sources
    default: op